version: '3'
services:
  myapp:
    image: khititach/node-express
    ports:
      - "3000:3000"
    command: "npm start"
db:
    image: 'mongo:3.6'
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:

